[package]
name = "mcu-leds"
version.workspace = true
edition.workspace = true

[dependencies]
embassy-rp.workspace = true
embassy-time.workspace = true
smart-leds.workspace = true
ws2812-pio.workspace = true
defmt.workspace = true
