apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: ${INFLUXDB_URL}
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: bvr
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: false
